export const mockedHotels = [
  {
    id: 1,
    name: "Hotel 1",
    address: "Address 1",
    city: "City 1",
    country: "Country 1",
    stars: 4.3,
    price: 100,
    image: "https://picsum.photos/200/300",
    features: ["Free Wifi", "Breakfast", "Air Conditioner", "Restaurant"],
  },
  {
    id: 2,
    name: "Hotel 2",
    address: "Address 2",
    city: "City 2",
    country: "Country 2",
    stars: 4.7,
    price: 200,
    image: "https://picsum.photos/200/300",
    features: ["Free Wifi", "Breakfast", "Air Conditioner", "Restaurant"],
  },
  {
    id: 3,
    name: "Hotel 3",
    address: "Address 3",
    city: "City 3",
    country: "Country 3",
    stars: 3.9,
    price: 300,
    image: "https://picsum.photos/200/300",
    features: ["Free Wifi", "Breakfast", "Air Conditioner", "Restaurant"],
  },
];
