<script>

  import { Title } from "@svelteuidev/core";

</script>
<vbox>
  <Title order={3} override={{fontWeight: 700}}>Description Hotel</Title>
  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor minus ex sint molestias ratione. Ipsum in sunt fugiat laudantium iusto et accusamus repellendus. Quibusdam autem doloribus dicta quam quae assumenda.</p>
  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor minus ex sint molestias ratione. Ipsum in sunt fugiat laudantium iusto et accusamus repellendus. Quibusdam autem doloribus dicta quam quae assumenda. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor minus ex sint molestias ratione. Ipsum in sunt fugiat laudantium iusto et accusamus repellendus. Quibusdam autem doloribus dicta quam quae assumenda. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor minus ex sint molestias ratione. Ipsum in sunt fugiat laudantium iusto et accusamus repellendus. Quibusdam autem doloribus dicta quam quae assumenda. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor minus ex sint molestias ratione. Ipsum in sunt fugiat laudantium iusto et accusamus repellendus. Quibusdam autem doloribus dicta quam quae assumenda. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor minus ex sint molestias ratione. Ipsum in sunt fugiat laudantium iusto et accusamus repellendus. Quibusdam autem doloribus dicta quam quae assumenda. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor minus ex sint molestias ratione. Ipsum in sunt fugiat laudantium iusto et accusamus repellendus. Quibusdam autem doloribus dicta quam quae assumenda.</p>
  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor minus ex sint molestias ratione. Ipsum in sunt fugiat laudantium iusto et accusamus repellendus. Quibusdam autem doloribus dicta quam quae assumenda.</p>
  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor minus ex sint molestias ratione. Ipsum in sunt fugiat laudantium iusto et accusamus repellendus. Quibusdam autem doloribus dicta quam quae assumenda.</p>
  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor minus ex sint molestias ratione. Ipsum in sunt fugiat laudantium iusto et accusamus repellendus. Quibusdam autem doloribus dicta quam quae assumenda.</p>
  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor minus ex sint molestias ratione. Ipsum in sunt fugiat laudantium iusto et accusamus repellendus. Quibusdam autem doloribus dicta quam quae assumenda. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor minus ex sint molestias ratione. Ipsum in sunt fugiat laudantium iusto et accusamus repellendus. Quibusdam autem doloribus dicta quam quae assumenda. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor minus ex sint molestias ratione. Ipsum in sunt fugiat laudantium iusto et accusamus repellendus. Quibusdam autem doloribus dicta quam quae assumenda. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor minus ex sint molestias ratione. Ipsum in sunt fugiat laudantium iusto et accusamus repellendus. Quibusdam autem doloribus dicta quam quae assumenda. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor minus ex sint molestias ratione. Ipsum in sunt fugiat laudantium iusto et accusamus repellendus. Quibusdam autem doloribus dicta quam quae assumenda.</p>
  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor minus ex sint molestias ratione. Ipsum in sunt fugiat laudantium iusto et accusamus repellendus. Quibusdam autem doloribus dicta quam quae assumenda.</p>
</vbox>